/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': '#121c28',
        'surface-variant': '#d9e3f4',
        'surface-container-highest': '#d9e3f4',
        'on-background': '#121c28',
        'on-error-container': '#93000a',
        secondary: '#006c49',
        primary: '#0a1422',
        tertiary: '#201100',
        'surface-bright': '#f8f9ff',
        'on-secondary': '#ffffff',
        'surface-container-high': '#dfe9fa',
        'on-secondary-fixed': '#002113',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#eaf1ff',
        'on-primary-fixed': '#121c2a',
        'primary-container': '#1f2937',
        'on-tertiary-container': '#c88000',
        'tertiary-container': '#3c2300',
        'on-tertiary-fixed-variant': '#653e00',
        'on-primary-fixed-variant': '#3d4756',
        error: '#ba1a1a',
        surface: '#f8f9ff',
        'inverse-primary': '#bdc7d9',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#005236',
        'on-tertiary-fixed': '#2a1700',
        'surface-tint': '#555f6f',
        'on-surface-variant': '#44474c',
        'primary-fixed-dim': '#bdc7d9',
        'primary-fixed': '#d9e3f6',
        'surface-container': '#e5eeff',
        background: '#f8f9ff',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#ffb95f',
        'on-secondary-container': '#00714d',
        'outline-variant': '#c5c6cc',
        'inverse-surface': '#27313e',
        outline: '#75777c',
        'secondary-container': '#6cf8bb',
        'surface-dim': '#d1dbec',
        'secondary-fixed': '#6ffbbe',
        'surface-container-low': '#eef4ff',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#ffddb8',
        'secondary-fixed-dim': '#4edea3',
        'on-primary-container': '#8690a1',
        'surface-container-lowest': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '4px',
        'margin-mobile': '16px',
        gutter: '16px',
        'margin-desktop': '32px',
        xl: '32px',
        lg: '24px',
        'container-max': '1440px',
        sm: '8px',
        base: '4px',
        md: '16px',
      },
      fontFamily: {
        'label-sm': ['Geist', 'sans-serif'],
        'mono-data': ['Geist', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '500' }],
        'mono-data': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-sm': ['18px', { lineHeight: '28px', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
